version: '3.8'
services:
  hub:
    image: selenium/hub:${SELENIUM_VERSION}
    ports:
      - 4442:4442
      - 4443:4443
      - 4444:4444
    deploy:
      replicas: 1
  chrome:
    image: selenium/node-chrome:${SELENIUM_VERSION}
    shm_size: 2g
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=true
    ports:
      - 6911-6913:5900
    deploy:
      replicas: 3
  firefox:
    image: selenium/node-firefox:${SELENIUM_VERSION}
    shm_size: 2g
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=true
    ports:
      - 6921-6923:5900
    deploy:
      replicas: 3
  edge:
    image: selenium/node-edge:${SELENIUM_VERSION}
    shm_size: 2g
    depends_on:
      - hub
    environment:
      - SE_EVENT_BUS_HOST=hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - VNC_NO_PASSWORD=true
    ports:
      - 6931-6933:5900
    deploy:
      replicas: 3
